$(document).ready(function(){
    $("button").click(function(){
        $("p.design").toggle();
    });
});
$(document).ready(function(){
    $("button").click(function(){
        $("p.development").toggle();
    });
});
